generic:
  - armours
  - assets
  - attributes
  - augmentations
  - backgrounds
  - bionics
  - corporations
  - countries
  - currencies
  - expertises
  - focuses
  - forms
  - gifts
  - identities
  - imperfections
  - locations
  - manifestations
  - milestones
  - natures
  - primals
  - shields
  - skills
  - software
  - species
  - spells
  - tactics
  - wealth
  - weaponmods
  - weapons